%% Read csv file generated by DeepLabCut
%  Author - Aamir Abbasi
%% --------------------------------------
clc;clear;close all;
start = tic;
disp('running...');
rootpath = 'E:\Aamir\BMI\';
savepath = 'E:\Aamir\BMI\';
cd(rootpath);
bmiBlocks = {'I076\Data\I076-201201-120931\'...
            ,'I076\Data\I076-201201-141645\'...
            ,'I076\Data\I076-201202-112106\'...
            ,'I076\Data\I076-201202-142652\'...
            ,'I076\Data\I076-201203-113433\'...
            ,'I076\Data\I076-201203-131642\'...
            ,'I076\Data\I076-201204-121406\'...
            ,'I076\Data\I076-201204-141944\'...
            ,'I076\Data\I076-201205-112030\'...
            ,'I076\Data\I076-201205-125511\'};

for j=1:length(bmiBlocks)
  
  % display current block
  disp(bmiBlocks{j});
  
  % Load cross-correlation data
  load([rootpath,bmiBlocks{j},'\CC_ForepawPipe_DLC.mat']);
  
  % Split it into early and late trials and take mean
  eT(j) = mean(squeeze(mean_C(1:floor(size(mean_C,2)/3))));
  lT(j) = mean(squeeze(mean_C(end-floor(size(mean_C,2)/3)+1:end)));
 
end

% Plot mean across sessions
bar([mean(eT),mean(lT)])

runTime = toc(start);
disp(['done! time elapsed (minutes) - ', num2str(runTime/60)]);

%%